import {defineField, defineType} from 'sanity'

export const loanApplication = defineType({
  name: 'loanApplication',
  title: 'Loan Application',
  type: 'document',
  groups: [
    {name: 'applicant', title: 'Applicant KYC'},
    {name: 'loanDetails', title: 'Facility & Terms'},
    {name: 'employment', title: 'Employment / Verification'},
    {name: 'admin', title: 'Staff & Status'},
  ],
  fields: [
    defineField({
      name: 'applicationReference',
      title: 'Tracking Reference',
      type: 'string',
      group: 'admin',
      description: 'System generated reference code (e.g. SKL-2026-123456)',
      readOnly: false,
    }),
    defineField({
      name: 'status',
      title: 'Application Status',
      type: 'string',
      group: 'admin',
      description: 'Current workflow status of this application',
      options: {
        list: [
          {title: '⏳ Pending Review', value: 'pending'},
          {title: '🔍 Under Review / KYC Check', value: 'reviewing'},
          {title: '✅ Approved', value: 'approved'},
          {title: '❌ Rejected', value: 'rejected'},
          {title: '🎉 Disbursed / Completed', value: 'completed'},
        ],
        layout: 'radio',
      },
      initialValue: 'pending',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'submittedAt',
      title: 'Submission Date & Time',
      type: 'datetime',
      group: 'admin',
      initialValue: () => new Date().toISOString(),
    }),
    defineField({
      name: 'adminNotes',
      title: 'Internal Credit Officer Notes',
      type: 'text',
      group: 'admin',
      rows: 4,
      description: 'Confidential staff notes regarding eligibility checks, verification calls, and disbursement status',
    }),
    defineField({
      name: 'fullName',
      title: 'Full Legal Name',
      type: 'string',
      group: 'applicant',
      description: 'Applicant name as it appears on official BVN / National ID',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'phone',
      title: 'Phone Number (WhatsApp Active)',
      type: 'string',
      group: 'applicant',
      description: 'e.g. 0803 000 0000',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'email',
      title: 'Email Address',
      type: 'string',
      group: 'applicant',
      validation: (Rule) => Rule.email(),
    }),
    defineField({
      name: 'state',
      title: 'State of Residence',
      type: 'string',
      group: 'applicant',
      description: 'State of residence in Nigeria',
      initialValue: 'FCT Abuja',
    }),
    defineField({
      name: 'city',
      title: 'Town / District',
      type: 'string',
      group: 'applicant',
      description: 'e.g. Utako, Garki, Ikeja, Yaba',
    }),
    defineField({
      name: 'loanProduct',
      title: 'Related Loan Product',
      type: 'reference',
      to: [{type: 'loanProduct'}],
      group: 'loanDetails',
      description: 'Link to the corresponding Loan Product in CMS (optional)',
    }),
    defineField({
      name: 'loanType',
      title: 'Loan Facility Category',
      type: 'string',
      group: 'loanDetails',
      options: {
        list: [
          {title: 'IPPIS Civil Service Loan', value: 'ippis'},
          {title: 'Collateral-Backed Loan', value: 'collateral'},
          {title: 'SME & Business Loan', value: 'business'},
          {title: 'Personal Emergency Loan', value: 'personal'},
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'requestedAmount',
      title: 'Requested Amount (₦)',
      type: 'number',
      group: 'loanDetails',
      description: 'Principal amount requested by the applicant (in Naira)',
      validation: (Rule) => Rule.required().positive().error('Requested amount must be greater than zero'),
    }),
    defineField({
      name: 'tenureMonths',
      title: 'Repayment Tenure (Months)',
      type: 'number',
      group: 'loanDetails',
      description: 'Tenure in months (1 - 36 months)',
      validation: (Rule) => Rule.required().min(1).max(36),
    }),
    defineField({
      name: 'purpose',
      title: 'Primary Purpose of Loan',
      type: 'string',
      group: 'loanDetails',
      description: 'e.g. Home Improvement, School Fees, Business Inventory',
    }),
    defineField({
      name: 'employmentType',
      title: 'Employment / Sector Status',
      type: 'string',
      group: 'employment',
      options: {
        list: [
          {title: 'Federal Civil Servant (IPPIS Enrolled)', value: 'civil_servant'},
          {title: 'Private Sector Professional', value: 'private_sector'},
          {title: 'Business Owner / Entrepreneur (MSME)', value: 'business_owner'},
          {title: 'Contractor / Vendor', value: 'contractor'},
          {title: 'Self-Employed / Other', value: 'other'},
        ],
      },
      initialValue: 'civil_servant',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'ippisNumber',
      title: 'IPPIS Number (Civil Servants)',
      type: 'string',
      group: 'employment',
      description: 'Mandatory for IPPIS loan processing (e.g. 123456)',
    }),
    defineField({
      name: 'ministryDepartmentAgency',
      title: 'Ministry, Department or Agency (MDA)',
      type: 'string',
      group: 'employment',
      description: 'e.g. Federal Ministry of Health, Federal Ministry of Education',
    }),
    defineField({
      name: 'collateralDescription',
      title: 'Collateral Asset Description',
      type: 'text',
      group: 'employment',
      rows: 3,
      description: 'For collateral loans: automobile or property particulars',
    }),
    defineField({
      name: 'agreedToTerms',
      title: 'Applicant Agreed to Verification Terms',
      type: 'boolean',
      group: 'applicant',
      initialValue: true,
      validation: (Rule) => Rule.required(),
    }),
  ],
  preview: {
    select: {
      fullName: 'fullName',
      phone: 'phone',
      amount: 'requestedAmount',
      loanType: 'loanType',
      status: 'status',
      ref: 'applicationReference',
    },
    prepare({fullName, phone, amount, loanType, status, ref}) {
      const formattedAmount = amount ? `₦${amount.toLocaleString('en-NG')}` : '₦0'
      const statusMap: Record<string, string> = {
        pending: '⏳ Pending',
        reviewing: '🔍 Reviewing',
        approved: '✅ Approved',
        rejected: '❌ Rejected',
        completed: '🎉 Disbursed',
      }
      return {
        title: `${fullName || 'Unnamed Applicant'} — ${formattedAmount}`,
        subtitle: `${ref ? `[${ref}] ` : ''}${loanType?.toUpperCase() || ''} | ${statusMap[status] || status || 'Pending'} | ${phone || ''}`,
      }
    },
  },
})
