import {defineArrayMember, defineField, defineType} from 'sanity'

export const loanProduct = defineType({
  name: 'loanProduct',
  title: 'Loan Product',
  type: 'document',
  groups: [
    {name: 'overview', title: 'Overview'},
    {name: 'terms', title: 'Terms & Limits'},
    {name: 'highlights', title: 'Highlights & Requirements'},
    {name: 'settings', title: 'Display Settings'},
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Product Name',
      type: 'string',
      group: 'overview',
      description: 'e.g. IPPIS Civil Service Loan, Collateral-Backed Loan, SME & Business Loan',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'overview',
      description: 'Unique URL identifier for frontend querying (e.g. ippis-loan, collateral-loan)',
      options: {
        source: 'name',
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      group: 'overview',
      description: 'Category key used for filtering and calculator associations on the frontend',
      options: {
        list: [
          {title: 'IPPIS Civil Service Loan', value: 'ippis'},
          {title: 'Collateral-Backed Loan', value: 'collateral'},
          {title: 'Business & SME Loan', value: 'business'},
          {title: 'Personal Emergency Loan', value: 'personal'},
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'badge',
      title: 'Product Badge',
      type: 'string',
      group: 'overview',
      description: 'Visual tag displayed above title (e.g. Most Popular, High Value Facility, Growth Capital, Fast Support)',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      group: 'overview',
      description: 'Short promotional subtitle (e.g. Exclusive credit solution for Federal Civil Servants on IPPIS)',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Full Description',
      type: 'text',
      group: 'overview',
      rows: 4,
      description: 'Comprehensive description explaining how the facility works and its value proposition',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'maxAmount',
      title: 'Maximum Amount (Display String)',
      type: 'string',
      group: 'terms',
      description: 'Display text on card (e.g. Up to ₦5,000,000 or Asset Value Dependent)',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'numericMinAmount',
      title: 'Minimum Loan Amount (₦ Numeric)',
      type: 'number',
      group: 'terms',
      description: 'Used by the interactive calculator (e.g. 100000)',
    }),
    defineField({
      name: 'numericMaxAmount',
      title: 'Maximum Loan Amount (₦ Numeric)',
      type: 'number',
      group: 'terms',
      description: 'Used by the interactive calculator (e.g. 5000000)',
    }),
    defineField({
      name: 'maxTenure',
      title: 'Maximum Tenure (Display String)',
      type: 'string',
      group: 'terms',
      description: 'Display text on card (e.g. Up to 24 Months, Flexible (Up to 36 Months))',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'numericMaxTenure',
      title: 'Maximum Tenure (Months Numeric)',
      type: 'number',
      group: 'terms',
      description: 'Used by the interactive calculator (e.g. 24 or 36)',
    }),
    defineField({
      name: 'monthlyInterestRate',
      title: 'Illustrative Monthly Interest Rate (%)',
      type: 'number',
      group: 'terms',
      description: 'Benchmark monthly percentage used for repayment estimation (e.g. 2.5 for 2.5%)',
    }),
    defineField({
      name: 'targetAudience',
      title: 'Target Eligibility / Audience',
      type: 'string',
      group: 'terms',
      description: 'Target demographic (e.g. Federal Ministry, Department & Agency (MDA) Staff)',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'popular',
      title: 'Is Popular / Featured Product?',
      type: 'boolean',
      group: 'settings',
      description: 'Featured product will be highlighted with a distinctive border and prominent styling',
      initialValue: false,
    }),
    defineField({
      name: 'features',
      title: 'Key Features / Highlights',
      type: 'array',
      group: 'highlights',
      description: 'Bullet points shown under Product Highlights on the product card',
      of: [defineArrayMember({type: 'string'})],
      validation: (Rule) => Rule.min(1).error('At least one feature is required'),
    }),
    defineField({
      name: 'requirements',
      title: 'Key Requirements',
      type: 'array',
      group: 'highlights',
      description: 'Documentation and eligibility items shown under Key Requirements',
      of: [defineArrayMember({type: 'string'})],
      validation: (Rule) => Rule.min(1).error('At least one requirement is required'),
    }),
    defineField({
      name: 'ctaText',
      title: 'CTA Button Text',
      type: 'string',
      group: 'settings',
      description: 'Button text (e.g. Apply for IPPIS Loan, Apply for Collateral Loan)',
      initialValue: 'Apply for Loan',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'displayOrder',
      title: 'Display Order',
      type: 'number',
      group: 'settings',
      description: 'Lower numbers appear first',
      initialValue: 0,
    }),
    defineField({
      name: 'isActive',
      title: 'Is Active / Published',
      type: 'boolean',
      group: 'settings',
      description: 'Uncheck to hide this product from the website without deleting it',
      initialValue: true,
    }),
  ],
  preview: {
    select: {
      title: 'name',
      badge: 'badge',
      maxAmount: 'maxAmount',
      popular: 'popular',
      isActive: 'isActive',
    },
    prepare({title, badge, maxAmount, popular, isActive}) {
      return {
        title: `${title} ${popular ? '⭐' : ''}`,
        subtitle: `${badge} • ${maxAmount || 'No amount limit'} ${!isActive ? '(Inactive)' : ''}`,
      }
    },
  },
})
