import {defineArrayMember, defineField, defineType} from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site Settings & Company Info',
  type: 'document',
  groups: [
    {name: 'company', title: 'Company Identity'},
    {name: 'contact', title: 'Contact Information'},
    {name: 'business', title: 'Business & Operations'},
    {name: 'social', title: 'Social Media'},
    {name: 'footer', title: 'Footer & Legal Links'},
    {name: 'seo', title: 'SEO & Metadata'},
    {name: 'trust', title: 'Trust & Process'},
  ],
  fields: [
    // ─── 1. Company Identity ──────────────────────────────────────────────────
    defineField({
      name: 'name',
      title: 'Business / Brand Name',
      type: 'string',
      group: 'company',
      description: 'Main display name of the brand (e.g. SilverKuun Loans)',
      initialValue: 'SilverKuun Loans',
      validation: (Rule) => Rule.required().error('Brand name is required'),
    }),
    defineField({
      name: 'legalName',
      title: 'Legal / Registered Name',
      type: 'string',
      group: 'company',
      description: 'Official registered cooperative entity name (e.g. SilverKuun Cooperative Multipurpose Society Limited)',
      initialValue: 'SilverKuun Cooperative Multipurpose Society Limited',
    }),
    defineField({
      name: 'groupName',
      title: 'Group / Parent Entity Name',
      type: 'string',
      group: 'company',
      description: 'Parent corporate entity name (e.g. SilverKuun Group)',
      initialValue: 'SilverKuun Group',
    }),
    defineField({
      name: 'tagline',
      title: 'Brand Tagline',
      type: 'string',
      group: 'company',
      description: 'Core marketing tagline (e.g. Reliable, Low-Interest Financial Solutions Tailored for Every Ambition)',
      initialValue: 'Reliable, Low-Interest Financial Solutions Tailored for Every Ambition',
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short Description',
      type: 'text',
      group: 'company',
      rows: 3,
      description: 'Concise summary of the organisation used for header snippets and summary cards',
      initialValue: 'A trusted Nigerian cooperative organisation delivering low-interest loan products, IPPIS civil servant salary facilities, collateral financing, and structured financial aid with transparency and ethical excellence.',
    }),
    defineField({
      name: 'aboutUs',
      title: 'About Us / Comprehensive Overview',
      type: 'text',
      group: 'company',
      rows: 5,
      description: 'Detailed company history, mission statement, and cooperative heritage',
    }),
    defineField({
      name: 'establishedYear',
      title: 'Year Established',
      type: 'string',
      group: 'company',
      description: 'Founding year (e.g. 2014)',
      initialValue: '2014',
    }),
    defineField({
      name: 'websiteUrl',
      title: 'Website URL',
      type: 'url',
      group: 'company',
      description: 'Primary public URL (e.g. https://silverkuunloans.com)',
      initialValue: 'https://silverkuunloans.com',
      validation: (Rule) => Rule.uri({scheme: ['http', 'https']}),
    }),
    defineField({
      name: 'logo',
      title: 'Company Logo',
      type: 'image',
      group: 'company',
      description: 'Main brand logo displayed across navigation headers and footer',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'favicon',
      title: 'Browser Favicon',
      type: 'image',
      group: 'company',
      description: 'Browser tab icon (recommended 32x32px or 64x64px PNG/ICO format)',
    }),

    // ─── 2. Contact Information ───────────────────────────────────────────────
    defineField({
      name: 'mainPhone',
      title: 'Main Phone Number',
      type: 'string',
      group: 'contact',
      description: 'Primary customer service hotline (e.g. +234 701 529 2816)',
      initialValue: '+234 701 529 2816',
      validation: (Rule) => Rule.required().error('Primary phone number is required'),
    }),
    defineField({
      name: 'alternatePhone',
      title: 'Alternate Phone Number',
      type: 'string',
      group: 'contact',
      description: 'Secondary contact line (e.g. +234 803 794 2635)',
      initialValue: '+234 803 794 2635',
    }),
    defineField({
      name: 'phones',
      title: 'All Customer Hotline Numbers',
      type: 'array',
      group: 'contact',
      description: 'Complete list of active phone numbers displayed across contact sections',
      of: [defineArrayMember({type: 'string'})],
      initialValue: ['+234 701 529 2816', '+234 803 794 2635'],
    }),
    defineField({
      name: 'whatsappNumber',
      title: 'WhatsApp Contact Line',
      type: 'string',
      group: 'contact',
      description: 'Official WhatsApp direct support line (e.g. +234 701 529 2816)',
      initialValue: '+234 701 529 2816',
    }),
    defineField({
      name: 'email',
      title: 'Primary Official Email',
      type: 'string',
      group: 'contact',
      description: 'Main enquiries inbox (e.g. info@silverkuunloans.com)',
      initialValue: 'info@silverkuunloans.com',
      validation: (Rule) => Rule.required().email().error('A valid email address is required'),
    }),
    defineField({
      name: 'supportEmail',
      title: 'Support / Helpdesk Email',
      type: 'string',
      group: 'contact',
      description: 'Dedicated customer helpdesk email (e.g. silverkuun@gmail.com)',
      initialValue: 'silverkuun@gmail.com',
      validation: (Rule) => Rule.email(),
    }),
    defineField({
      name: 'emails',
      title: 'All Official Email Addresses',
      type: 'array',
      group: 'contact',
      description: 'List of all published corporate email addresses',
      of: [defineArrayMember({type: 'string'})],
      initialValue: ['info@silverkuunloans.com', 'silverkuun@gmail.com'],
    }),
    defineField({
      name: 'headquartersAddress',
      title: 'Headquarters Physical Address',
      type: 'string',
      group: 'contact',
      description: 'Primary office location (e.g. Plot 418, Utako Commercial Hub, FCT Abuja)',
      initialValue: 'Plot 418, Utako Commercial Hub, FCT Abuja',
    }),
    defineField({
      name: 'city',
      title: 'Headquarters City',
      type: 'string',
      group: 'contact',
      description: 'City of primary headquarters (e.g. Abuja)',
      initialValue: 'Abuja',
    }),
    defineField({
      name: 'state',
      title: 'Headquarters State / Region',
      type: 'string',
      group: 'contact',
      description: 'State / Federal Territory (e.g. FCT Abuja)',
      initialValue: 'FCT Abuja',
    }),
    defineField({
      name: 'country',
      title: 'Country',
      type: 'string',
      group: 'contact',
      description: 'Country of registration and primary operation',
      initialValue: 'Nigeria',
    }),
    defineField({
      name: 'mapsUrl',
      title: 'Google Maps / Location URL',
      type: 'url',
      group: 'contact',
      description: 'Link to Google Maps location for the headquarters office',
      validation: (Rule) => Rule.uri({scheme: ['http', 'https']}),
    }),

    // ─── 3. Business & Operations ────────────────────────────────────────────
    defineField({
      name: 'workingHours',
      title: 'Standard Operating Hours',
      type: 'string',
      group: 'business',
      description: 'Branch operational hours (e.g. Monday – Friday: 9:00 AM – 4:30 PM)',
      initialValue: 'Monday – Friday: 9:00 AM – 4:30 PM',
    }),
    defineField({
      name: 'supportHours',
      title: 'Support / Helpdesk Hours',
      type: 'string',
      group: 'business',
      description: 'Online and telephone helpdesk availability (e.g. 24/7 Dedicated Support Helpdesk)',
      initialValue: '24/7 Dedicated Support Helpdesk',
    }),
    defineField({
      name: 'areasServed',
      title: 'Geographic Areas Served',
      type: 'string',
      group: 'business',
      description: 'Operational reach (e.g. Abuja, Lagos, and Nationwide for Federal Civil Servants)',
      initialValue: 'Abuja, Lagos, and Nationwide for Federal Civil Servants',
    }),
    defineField({
      name: 'registrationNumber',
      title: 'Cooperative Registration Details',
      type: 'string',
      group: 'business',
      description: 'Cooperative society registration reference under the Nigerian Cooperative Societies Act',
      initialValue: 'SilverKuun Cooperative Multipurpose Society Limited',
    }),
    defineField({
      name: 'regulatoryInfo',
      title: 'Regulatory & Compliance Information',
      type: 'text',
      group: 'business',
      rows: 3,
      description: 'Legal compliance note regarding credit checks, cooperative bylaws, and IPPIS deductions',
      initialValue: 'Operating under the Nigerian Cooperative Societies regulatory framework. All IPPIS loan facilities are processed in strict compliance with Federal Civil Service payroll remittance guidelines.',
    }),
    defineField({
      name: 'yearsOfExcellence',
      title: 'Years of Excellence (Display Metric)',
      type: 'string',
      group: 'business',
      description: 'Prominent trust metric displayed on Hero and About banners (e.g. 10+)',
      initialValue: '10+',
    }),
    defineField({
      name: 'totalDisbursed',
      title: 'Total Disbursed (Display Metric)',
      type: 'string',
      group: 'business',
      description: 'Cumulative credit volume disbursed (e.g. ₦2.5B+)',
      initialValue: '₦2.5B+',
    }),
    defineField({
      name: 'satisfiedMembers',
      title: 'Satisfied Members (Display Metric)',
      type: 'string',
      group: 'business',
      description: 'Member count metric (e.g. Thousands+)',
      initialValue: 'Thousands+',
    }),
    defineField({
      name: 'ippisMaxLimit',
      title: 'IPPIS Maximum Facility Limit (Display Metric)',
      type: 'string',
      group: 'business',
      description: 'Maximum credit ceiling for federal civil servants (e.g. ₦5,000,000)',
      initialValue: '₦5,000,000',
    }),

    // ─── 4. Social Media ─────────────────────────────────────────────────────
    defineField({
      name: 'facebook',
      title: 'Facebook Page URL',
      type: 'url',
      group: 'social',
      description: 'Official Facebook profile or page link',
      validation: (Rule) => Rule.uri({scheme: ['http', 'https']}),
    }),
    defineField({
      name: 'instagram',
      title: 'Instagram Profile URL',
      type: 'url',
      group: 'social',
      description: 'Official Instagram profile link',
      validation: (Rule) => Rule.uri({scheme: ['http', 'https']}),
    }),
    defineField({
      name: 'twitter',
      title: 'X / Twitter Profile URL',
      type: 'url',
      group: 'social',
      description: 'Official X (formerly Twitter) profile link',
      validation: (Rule) => Rule.uri({scheme: ['http', 'https']}),
    }),
    defineField({
      name: 'linkedin',
      title: 'LinkedIn Company URL',
      type: 'url',
      group: 'social',
      description: 'Official LinkedIn company page link',
      validation: (Rule) => Rule.uri({scheme: ['http', 'https']}),
    }),
    defineField({
      name: 'whatsapp',
      title: 'WhatsApp Click-to-Chat Link',
      type: 'url',
      group: 'social',
      description: 'Direct WhatsApp link (e.g. https://wa.me/2347015292816)',
      initialValue: 'https://wa.me/2347015292816',
      validation: (Rule) => Rule.uri({scheme: ['http', 'https']}),
    }),
    defineField({
      name: 'youtube',
      title: 'YouTube Channel URL',
      type: 'url',
      group: 'social',
      description: 'Official YouTube channel link',
      validation: (Rule) => Rule.uri({scheme: ['http', 'https']}),
    }),
    defineField({
      name: 'tiktok',
      title: 'TikTok Profile URL',
      type: 'url',
      group: 'social',
      description: 'Official TikTok page link',
      validation: (Rule) => Rule.uri({scheme: ['http', 'https']}),
    }),

    // ─── 5. Footer & Legal Links ─────────────────────────────────────────────
    defineField({
      name: 'footerDescription',
      title: 'Footer Brand Description',
      type: 'text',
      group: 'footer',
      rows: 3,
      description: 'Short statement displayed in the footer column below the logo',
      initialValue: 'A trusted Nigerian cooperative organisation delivering low-interest loan products, IPPIS civil servant salary facilities, collateral financing, and structured financial aid with transparency and ethical excellence.',
    }),
    defineField({
      name: 'copyrightText',
      title: 'Copyright Notice',
      type: 'string',
      group: 'footer',
      description: 'Copyright statement (use {year} for dynamic year insertion)',
      initialValue: 'SilverKuun Loans. Operating under SilverKuun Cooperative Multipurpose Society Limited.',
    }),
    defineField({
      name: 'disclaimerText',
      title: 'Legal Disclaimer Text',
      type: 'text',
      group: 'footer',
      rows: 2,
      description: 'Regulatory note displayed at the bottom of the page',
      initialValue: 'All loans are subject to verified credit assessment and eligibility confirmation. Terms and conditions apply.',
    }),
    defineField({
      name: 'privacyPolicyUrl',
      title: 'Privacy Policy Path / URL',
      type: 'string',
      group: 'footer',
      description: 'URL or section anchor for the Privacy Policy (e.g. #help or /privacy-policy)',
      initialValue: '#help',
    }),
    defineField({
      name: 'termsUrl',
      title: 'Terms of Service Path / URL',
      type: 'string',
      group: 'footer',
      description: 'URL or section anchor for Terms of Service (e.g. #help or /terms)',
      initialValue: '#help',
    }),
    defineField({
      name: 'bylawsUrl',
      title: 'Cooperative Bylaws Path / URL',
      type: 'string',
      group: 'footer',
      description: 'URL or section anchor for Cooperative Bylaws (e.g. #help)',
      initialValue: '#help',
    }),

    // ─── 6. SEO & Metadata ───────────────────────────────────────────────────
    defineField({
      name: 'metaTitle',
      title: 'Default Meta Title',
      type: 'string',
      group: 'seo',
      description: 'Page title displayed in search engines and browser tabs',
      initialValue: 'SilverKuun Loans | Low Interest Loans & Financial Solutions in Nigeria',
      validation: (Rule) => Rule.max(70).warning('Titles longer than 70 characters may be truncated by search engines'),
    }),
    defineField({
      name: 'metaDescription',
      title: 'Default Meta Description',
      type: 'text',
      group: 'seo',
      rows: 3,
      description: 'Snippet shown in search results and social previews (recommended 150-160 characters)',
      initialValue: 'Access low-interest IPPIS loans up to ₦5M, collateral loans, business financing, and financial aid in Nigeria with SilverKuun Cooperative Multipurpose Society.',
      validation: (Rule) => Rule.max(200).warning('Descriptions longer than 200 characters may be truncated by search engines'),
    }),
    defineField({
      name: 'ogImage',
      title: 'Default Social Sharing Image (OG Image)',
      type: 'image',
      group: 'seo',
      description: 'Featured image displayed when links are shared on Facebook, X/Twitter, WhatsApp, and LinkedIn (recommended 1200×630px)',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'keywords',
      title: 'Meta Search Keywords',
      type: 'array',
      group: 'seo',
      description: 'Key terms associated with the platform for metadata and discoverability',
      of: [defineArrayMember({type: 'string'})],
      initialValue: [
        'SilverKuun Loans',
        'IPPIS Loans Nigeria',
        'Civil Servant Loans',
        'Collateral Loans Nigeria',
        'Business Financing',
        'Cooperative Loans Abuja',
        'Low Interest Loans Nigeria',
      ],
    }),
    defineField({
      name: 'canonicalUrl',
      title: 'Canonical Website URL',
      type: 'url',
      group: 'seo',
      description: 'Primary canonical base URL for search engines (e.g. https://silverkuunloans.com)',
      initialValue: 'https://silverkuunloans.com',
      validation: (Rule) => Rule.uri({scheme: ['http', 'https']}),
    }),

    // ─── 7. Trust & Process ──────────────────────────────────────────────────
    defineField({
      name: 'officeLocations',
      title: 'Branch Office Locations',
      type: 'array',
      group: 'trust',
      description: 'All physical branch locations (Abuja & Lagos). Used in ContactSection and Footer.',
      of: [defineArrayMember({type: 'officeLocation'})],
    }),
    defineField({
      name: 'whyChoosePoints',
      title: 'Why SilverKuun — Trust Points',
      type: 'array',
      group: 'trust',
      description: 'The 6 cooperative heritage and trust pillars displayed in the WhySilverkuun section',
      of: [defineArrayMember({type: 'whyChoosePoint'})],
    }),
    defineField({
      name: 'processSteps',
      title: 'How It Works — Process Steps',
      type: 'array',
      group: 'trust',
      description: 'The 4-step application journey displayed in the HowItWorks section',
      of: [defineArrayMember({type: 'processStep'})],
    }),
  ],
  preview: {
    select: {
      name: 'name',
      legalName: 'legalName',
    },
    prepare({name, legalName}) {
      return {
        title: name ? `${name} — Site Settings` : 'KuunLoans — Site Settings',
        subtitle: legalName || 'Global Site Settings & Company Info',
      }
    },
  },
})
